### ISSUE TITLE
Could not find zeppelin-solidity/contracts/SafeMath.sol

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-contracts#1]
Hi,

running npm install:
`Could not find zeppelin-solidity/contracts/SafeMath.sol from any sources; imported from /home/enrico/paratii/paratii-contract/contracts/paratii/DayLimitAccount.sol
`
how can i fix it?
Ty!

**Comment by jellegerbrandy** [comment]
zeppelin moved the contract to `contracts/math/SafeMath.sol`. so it broke on upgrade. 

you can fix it by changing the import paths and make a PR :-)
