### ISSUE TITLE
upgrade to solidity 0.4.18

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#11]
https://github.com/ethereum/solidity/releases

**Comment by aeftimia** [comment]
I get this error when I don't [update truffle to v4](https://github.com/Paratii-Video/paratii-contracts/issues/20)
>SyntaxError: Source file requires different compiler version (current compiler is 0.4.15+commit.bbb8e64f.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version

So it looks like this may be dependent on [issue20](https://github.com/Paratii-Video/paratii-contracts/issues/20)

**Comment by jellegerbrandy** [comment]
I think you need the update the `pragma` statement at the beginning of the files, `pragma solidity ^0.4.13;` to the latest version of solidity.

**Comment by aeftimia** [comment]
It seems Truffle 3 is packaged with Solidity 0.4.15, so you can't go higher than that without [upgrading to Truffle 4](https://github.com/Paratii-Video/paratii-contracts/issues/20).

**Comment by jellegerbrandy** [comment]
I say we do the upgrade.
