### ISSUE TITLE
Pay-per-view contract scheme

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-contracts#2]
Currently, when a video is purchased, we are sending PTI to the producer address + validating the transaction. To be more modular and evolve more flexibly (revenue splitting and so forth), we can have a contract for the content (or a contract for the creator that's updated with references to newly uploaded content) + transaction to this contract.

**Comment by jellegerbrandy** [comment]
There is now a VideoStore contract that sends the money to both owner of the video as well as to the Paratii redistribution pool. This contract can be at a later date extended/changed.
