### ISSUE TITLE
complete videoregistry data model

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#4]
The objectst that we are workign with in the app look like this:

```
  {
    _id: '5',
    title: 'Around the Block - Teaser 16',
    description: 'Another teaser of Around the Block ',
    thumb: '/img/cover/teaser16.jpg',
    duration: '03:22',
    price: 14,
    uploader: {
      address: '0xe19678107410951a9ed1f6906ba4c913eb0e44d4',
      name: 'Paratii',
      avatar: 'http://i.pravatar.cc/150?img=4'
    },
    stats: {
      likes_percentage: 98,
      views: 100,
      likes: 500,
      dislikes: 7
    },
    tags: ['WEBTORRENT', 'AROUND THE BLOCK'],
    src: 'magnet:?xt=urn:btih:826bfc8069e71418c215179f12546460e3364b5a&dn=Around_The_Block_Teaser_16.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com',
    mimetype: 'video/mp4'
  },
```

**Comment by aeftimia** [comment]
I've been looking into porting this onto the blockchain. I was thinking the `uploader` section should go into a `struct` stored in a separate contract called `UserRegistry`. `UserRegistry` will work in an analogous manner to `VideoRegistry`. `UserRegistry` could keep track of user metadata and store an address of the user. 

The `VideoRegistry` contract would then keep track of metadata. This includes the following for each video:

```
string public title;
string public description;
address public thumb; //ipfs address of thumbnail photo
unit public duration; //in milliseconds
uint public price; // might be changed to an address of a contract with a callback that determines price dynamically in the future.
address public uploader; //address stored in the user registry that maps to user metadata
struct public stats; // this is initialized with zeros for likes_percentage, views, likes, and dislikes
string[] public tags; // list of tags
string public src; 
```

As a side note, I think `tags` should be stored within `stats`. Furthermore, I think `tags` will carry more predictive value if it's a map from strings (the tag itself) to lists of addresses of users (corresponding to an address in the `UserRegistry`) that voted for each of those strings as tags. Then you can analyze what types of people tag what videos if you want. A simpler version would be to just map the strings to a tally that tracks how many users tagged the video with each tag.

I also suspect that things will become easier to follow and maintain when any action that results in an exchange of PTI or ETH go in a separate contract--including stats. So when you *like* a video, there's an exchange of tokens or ETH, and this should go into a `Like` contract that exchanges currency and updates corresponding metadata stored in other contracts. Metadata should only be able to be updated by the core Paratii contracts for security.

**Comment by jellegerbrandy** [comment]
I agree with the last point about generic contracts, but  move that discussion to a new issue #8.

Let's here just focus in the VideoRegistry contract. Data definition looks fine to me, and there already is a UserRegistry contract, so we can just start implementing it.
