### ISSUE TITLE
write tests for 'onlyOnWhiteList' in ParatiiAvatar

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#5]

**Comment by jellegerbrandy** [comment]
there is an implementation of the `onlyOnWhitelist` modifier, but it has not been tested yet (there are 2 stubs marked with [TODO] in `tests/paratiiAvatar.js`)

**Comment by aeftimia** [comment]
Should this be closed? I dd not see a TODO in `paratiiAvatar.js`

**Comment by jellegerbrandy** [comment]
Looking at the code of ParatiiAvatar.sol, it seems that the  `onlyOnWhitelist` modifier is implemented. There are no tests for it, though. (We need some simple test checking that non-whitelist addresses cannot control the avatar). 
I changed the title.
