### ISSUE TITLE
Build tests in Solidity 

### ISSUE THREAD

**Issue by luisfidelis** [Paratii-Video/paratii-contracts#53]
Javascript tests cannot deal with the return of functions, so, i think it's necessary.

* Use Truffle's test support to create assertions in Solidity

**Comment by jellegerbrandy** [comment]
you are right that is a limit of javascript testing, but we have not felt the need. I'm not sure if we have many functions that return a non-trivial return value, and almost all functions log an event with their results.

So I agree with you that it would be good, but I'm not sure if it is worth the overhead of writing and maintaining them.

**Comment by luisfidelis** [comment]
I agree with you. It might be useful in the future, when considering third-party contracts interacting with Paratii. Smart contracts cannot listen to events of another contract, but it involves the addition of non-trivial return as well.
