### ISSUE TITLE
create a "likesRegistry" contract

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#6]
this contract will be used to register the likes of videos by particular users - i.e. it will have "entries" with a videoId and an account and perhaps some other infomration (blockNumber?)

**Comment by jellegerbrandy** [comment]
un the current (20171014) version the likes are registered using the `likeVideo()` function (which is defined in the `UserRegistry`). So this would need to be ported to the new contract (and removed from the usrregistry contrat)

**Comment by aeftimia** [comment]
I was thinking we'd have a “like” function that takes a videohash as an argument (that matches something in the video registry). Then the function appends the `msg.sender` to a list associated with the videohash.
You can likewise store a list of video hashes for each user that likes a video.

If we wanted to store metadata on IPFS, the `UserRegistry` and the `VideoRegistry` should also contain a metadata hash pointer with a pointer to a data structure on IPFS which stores metadata. 

The problem of course is that metadata will constantly be changing, so this hash will be as well. Fortunately, there seems to be work on static pointers in IPFS called [IPNS](https://flyingzumwalt.github.io/ipfs-tutorials/curriculum/files-on-ipfs/modules/update-files/).

**Comment by jellegerbrandy** [comment]
- Just to be clear: a working and somewhat tested `like` functino is already there: https://github.com/Paratii-Video/paratii-contracts/blob/master/contracts/paratii/UserRegistry.sol#L61  - we are talking about storing the likes in a different way.
- Small detail: now, in the code, videos are identified by a string (referred to in the code as `videoId`) (not a hash).
- The name system thing is not a real solution. The point of having data on the blockchain is that there can be no doubt that the data are those and not others. If we can change data outside of the blockchain, we introduce the trust factor again (we must trust whoever is conrolling ipns, in this case). So what the "use-a-hash-to-point-to-data-outside-of-the-blockchain" pattern gives us is a way lowering the cost of storing data on the blockchain (at the price of having that data not accessible directly anymore), but it does not avoid the fat that each time we change the data, we need to change the hash on the blockchain. 
-

**Comment by jellegerbrandy** [comment]
In any case, the structure shoudl be as in #8
