### ISSUE TITLE
register the acquisitions

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#7]
If a user buys a video (if `buyVideo()` is called), the fact that the user now owns the video needs to be registered somewhere. 

We need a `Acquisitions` (or a better name) contract that will be very similar to the `Likes` contract (#6), and hook it up with the `buyVideo` function.

**Comment by aeftimia** [comment]
I'm looking into creating an abstract contract or interface with some reusable code we can use for this, the LikeRegistry, and other contracts that involve a financial transaction and log of metadata between users and videos.

**Comment by aeftimia** [comment]
This is now done within the `isAcquired` field in `UserRegistry.videos` in the branch [issue3](https://github.com/Paratii-Video/paratii-contracts/tree/issue3).
